version: 0.0.0.{build}
init:
- cmd: ''
environment:
  QTDIR: C:\Qt\5.6.3\mingw49_32
  MINGW: C:\Qt\Tools\mingw492_32\bin
  CMAKE: C:\Program Files (x86)\CMake\bin
  FOREPLAYER_OUTPUT_PATH: c:\foreplayer
  QTMINGW: C:\Qt\Qt5.6.3\Tools\mingw492_32\bin
  NSIS: C:\Program Files (x86)\NSIS
  ZIP: C:\Program Files\7-Zip
  PYTHON: C:\Python34
  CXX_BUILD_CORES: 8
install:
- cmd: ''
build_script:
- cmd: >-
    set OLD_PATH=%PATH%

    FOR /F "tokens=*" %%i in ('git describe') do SET COMMITNOW=%%i

    set VERSION_DATE=%DATE:~10,4%.%DATE:~4,2%.%DATE:~7,2%

    if defined APPVEYOR_REPO_TAG_NAME set APPVEYOR_BUILD_VERSION=%APPVEYOR_REPO_TAG_NAME%.%APPVEYOR_BUILD_NUMBER%

    set FOREPLAYER_VERSION=%APPVEYOR_BUILD_VERSION%


    set PATH=%QTDIR%;%MINGW%;%CMAKE%;%NSIS%;%ZIP%;

    call sdk\build.bat


    set PATH=%PATH%;%PYTHON%

    set FOREPLAYER_VERSION=%APPVEYOR_BUILD_VERSION%

    cd desktop\app\version

    python gen_win32.py

    cd ..\..\..

    call desktop\build.bat


    cd dist\win32

    call prepare.bat

    7z a -x@7zignore.txt Foreplayer%FOREPLAYER_VERSION%.7z *

    7z a -x@7zignore.txt Foreplayer%FOREPLAYER_VERSION%.zip *

    makensis install.nsi

    cd ..\..
artifacts:
- path: dist/win32/Foreplayer*.zip
  name: archive
- path: dist/win32/Foreplayer*.7z
  name: 7zarchive
- path: dist/win32/Foreplayer*-Setup.exe
  name: installer
deploy:
- provider: GitHub
  auth_token:
    secure: icaJlPkqzI3IUxSqUHgI34BtCpffDWxpp4otuYUAwA1RqMtQvAtdmXjOL9UOdqQI
  artifact: /Foreplayer.*\.(exe|7z|zip)/
  draft: true
  force_update: false
  on:
    appveyor_repo_tag: true
notifications:
- provider: Email
  to:
  - wazcd_1608@qq.com
  subject: Build status of foreplayer
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false