#ifndef PCH_H
#define PCH_H

#include <QMap>
#include <QFont>
#include <QRect>
#include <QSize>
#include <QFile>
#include <QIcon>
#include <QMenu>
#include <QPropertyAnimation>
#include <QPainter>
#include <QLabel>
#include <QTimer>
#include <QBrush>
#include <QPoint>
#include <QEvent>
#include <QDebug>
#include <QColor>
#include <QDate>
#include <QList>
#include <QString>
#include <QJsonValue>
#include <QJsonArray>
#include <QApplication>
#include <QFont>
#include <QLibrary>
#include <QJsonObject>
#include <QHash>
#include <QVariant>

#include <QObject>
#include <QObject>
#include <QApplication>
#include <QFont>
#include <QDir>
#include <QDebug>
#include <QAbstractListModel>
#include <QAbstractTableModel>
#include <QWidget>
#include <QBitmap>
#include <QPixmap>
#include <QObject>
#include <QPointF>
#include <QThread>
#include <QString>
#include <QSlider>
#include <QDomNode>
#include <QPainter>
#include <QToolBar>
#include <QFileInfo>
#include <QCheckBox>
#include <QListView>
#include <QSplitter>
#include <QScrollBar>
#include <QTableView>
#include <QFileDialog>
#include <QMainWindow>
#include <QMouseEvent>
#include <QPaintEvent>
#include <QPushButton>
#include <QSizePolicy>
#include <QStringList>
#include <QVBoxLayout>
#include <QApplication>
#include <QDomDocument>
#include <QCommonStyle>
#include <QDomNodeList>
#include <QStylePainter>
#include <QDesktopWidget>
#include <QLinearGradient>
#include <QSystemTrayIcon>
#include <QXmlStreamReader>
#include <QContextMenuEvent>
#include <QStyleOptionButton>
#include <QStyleOptionComplex>

#endif // PCH_H

